### PR TITLE
Create ja.cfg

### LINKED ISSUE #20: Japanese (日本語) <ja.cfg>
# Localization - ![日本語][JA] Japanese(日本語) <ja.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[ja.cfg] 🗃️

### Translation

* [x] ![日本語][JA] Japanese(日本語) <ja.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[JA]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Japanese-flag-sm.png "日本語"

### PR DESCRIPTION
**Pull request by zer0Kerbal**
add Japanese localization

closes #20 - Japanese (日本語) <ja.cfg>

### CODE REVIEW

**Review by Lisias — COMMENTED** [review]
私にはうまく見えます！
(Google 翻訳者が助けてくれます!)

**Comment by Lisias** [comment]
Merged!

**Comment by zer0Kerbal** [comment]
> Closed with unmerged commits
> This pull request is closed, but the dev/Z/localization-ja branch has unmerged commits.

?

**Comment by Lisias** [comment]
damn! How in hell I closed this one without merging it??? #facePalm

**Comment by Lisias** [comment]
Ok, **NOW** I merged it. Proceeding with the release.

**Comment by zer0Kerbal** [comment]
> damn! How in hell I closed this one without merging it??? #facePalm

blame it on the 😷!

**Pull request merged**
