### PR TITLE
Dev/z/gh pages/change logs

### PR DESCRIPTION
**Pull request by zer0Kerbal**

### CODE REVIEW

**Review by zer0Kerbal — COMMENTED** [review]
📑

**Comment by Lisias** [comment]
Hi! 

O noticed that `lisias` and `LisiasT` were added to tags on the `LegalMumboJumbo.md` file, and then removed. Didn't understood what happened!

What are the meaning of the tags on this file?

**Comment by zer0Kerbal** [comment]
> Hi!
> 
> O noticed that `lisias` and `LisiasT` were added to tags on the `LegalMumboJumbo.md` file, and then removed. Didn't understood what happened!
> 
> What are the meaning of the tags on this file?

I put them back; accidentally removed - then put back.

search tags - like seo (I think)

**Review by zer0Kerbal — COMMENTED** [review]
🪅

**Pull request merged**
